#!/bin/zsh
# Build Vibey for iOS and install it on Jack's iPhone (wireless works if paired).
#   ./build.sh            device build + install
#   ./build.sh sim        simulator build only
set -euo pipefail
cd "$(dirname "$0")"
ROOT=../..

# Secrets.swift is generated, gitignored, and holds the app token from .env.
TOKEN=$(grep -E '^VIBEY_APP_TOKEN=' "$ROOT/.env" 2>/dev/null | cut -d= -f2- || true)
HOST=$(ipconfig getifaddr en0 2>/dev/null || echo "Jacks-MacBook-Pro-6.local")
umask 077
cat > Vibey/Core/Secrets.swift <<SWIFT
// Generated by build.sh. Do not commit.
enum Secrets {
    static let token = "${TOKEN}"
    static let host = "${HOST}"
}
SWIFT

xcodegen generate --quiet

if [[ "${1:-}" == "sim" ]]; then
  xcodebuild -project Vibey.xcodeproj -scheme Vibey -configuration Debug \
    -destination 'generic/platform=iOS Simulator' -derivedDataPath build/sim build -quiet
  echo "built build/sim/Build/Products/Debug-iphonesimulator/Vibey.app"
  exit 0
fi

KEY=D64LNK6B96
xcodebuild -project Vibey.xcodeproj -scheme Vibey -configuration Debug \
  -destination 'generic/platform=iOS' -derivedDataPath build/device \
  -allowProvisioningUpdates \
  -authenticationKeyPath "$HOME/.appstoreconnect/private_keys/AuthKey_${KEY}.p8" \
  -authenticationKeyID "$KEY" \
  -authenticationKeyIssuerID 30502701-dad4-4788-9777-3a7c61beeac5 \
  build -quiet

DEVICE=${VIBEY_DEVICE:-$(xcrun devicectl list devices 2>/dev/null | awk '/available \(paired\)/ && /iPhone/ {for(i=1;i<=NF;i++) if ($i ~ /^[0-9A-F-]{36}$/) {print $i; exit}}')}
[[ -n "$DEVICE" ]] || { echo "no paired iPhone available"; exit 1; }
xcrun devicectl device install app --device "$DEVICE" build/device/Build/Products/Debug-iphoneos/Vibey.app
xcrun devicectl device process launch --device "$DEVICE" com.jackmielke.vibey || true
